### ISSUE TITLE
Image scaling is using default method, resulting in blur when sprites are scaled up

### ISSUE THREAD

**Issue by pixelbath** [kesiev/rewtro#3]
When sprites are scaled up, they are not using crisp (nearest neighbor) scaling:

![image](https://user-images.githubusercontent.com/4740954/72003439-9d642500-3206-11ea-978a-ec83ecc27466.png)

See this page for implementation details for different scaling methods: https://lospec.com/browser-image-scaling-comparison/

**Comment by kesiev** [comment]
Aww. Code was there, never worked. I should have fixed that locally - committing everything this weekend. Thanks!
