### ISSUE TITLE
Unable to use "Load from QR" on desktop

### ISSUE THREAD

**Issue by pixelbath** [kesiev/rewtro#4]
When pressing the "Load QR-Cart" button, the browser grays out the screen and will not allow me to close the popup. The browser does *not* prompt for use of the host camera.

Errors on Chrome:
![image](https://user-images.githubusercontent.com/4740954/72003694-24b19880-3207-11ea-8fc1-4243c6e3280a.png)

Error on Firefox:
![image](https://user-images.githubusercontent.com/4740954/72003761-4c086580-3207-11ea-81ac-1ffdadd539d2.png)

OS: Windows 10
Browser: Chrome (latest), Firefox (latest)

**Comment by kesiev** [comment]
I'm testing the https://www.kesiev.com/rewtro instance on Windows 10 Home, using Chrome 79.0.3945.117 and Firefox 72.0.1. Both browsers says that there aren't any updates.
When opening the Rewtro camera, it asks for permission and, once accepted, it works normally.

Denied permissions are still unhandled and crashes Rewtro the way you are saying- I'll give a shot to that feature ASAP - but the permission denied console error gives a different error:

Chrome: `(index):1 Uncaught (in promise) DOMException: Permission denied`
Firefox: `uncaught exception: Object`

Reading your errors looks like the whole `mediaDevices` object is missing or different.

Am I missing some detail? Are we using the same browser version? Are you using any plugin?

**Comment by pixelbath** [comment]
It looks like we're using the same browser versions. I don't have camera access explicitly blocked for any websites. I do use uBlock Origin, but disabling that has no effect. I'll experiment with it on my side and see if I can figure out what's going on.

**Comment by kesiev** [comment]
Closing this issue for its ~2yrs birthday ;)
