### ISSUE TITLE
Feature Request: Link to /carts

### ISSUE THREAD

**Issue by pixelbath** [kesiev/rewtro#5]
Currently, the `/carts` folder must be navigated to manually. I would like a link on the main Rewtro page pointing to this folder to make it easier to browse carts.

**Comment by kesiev** [comment]
I'd like to keep the Rewtro console as much _player first_ as I can and the basic concept is that games are mainly _loaded offline_ from animated GIFs or papercrafts, without any online cartridges list. Moreover parents are scared by developer tools. :)

Anyway the feature you are suggesting is good for developers so I'm thinking about adding a _developer mode_ you can enable to your local Rewtro console from the SDK interface. When enabled a new icon that links to the `/carts` folder appears on the dashboard - and may do other things in the future.

What do you think?

**Comment by pixelbath** [comment]
That sounds pretty workable for me, given your goals for the project. I'll close this issue out.

**Comment by kesiev** [comment]
This request has been implemented and committed. Hope it will help! Thanks!
